#!/usr/bin/env bash
#
###############################################################################
# Environment
###############################################################################

# $_ME
#
# This program's basename.
_ME="$(basename "${0}")"

###############################################################################
# Help
###############################################################################

# _print_help()
#
# Usage:
#   _print_help
#
# Print the program help information.
_print_help() {
    cat <<HEREDOC
This script will set up the scripts in "https://github.com/BizTheDad/scripts" on
your PC. Also, the "https://github.com/BizTheDad/inpval/blob/main/executable/inpval"
executable will be downloaded and set up.

If it doesn't already exist, the "$HOME/bin" directory will be created. This
directory is where all executables will be stored.

Usage:
  sudo ${_ME}
  ${_ME} -h | --help

Options:
  -h --help  Show this screen.
HEREDOC
}

###############################################################################
# Functions
###############################################################################
_get_script() {
    dir="$HOME/bin/"
    file="$1"
    url="$2"
    if [[ -f "$dir$file" ]]
    then
        echo "Removing current '$file'"
        rm "$dir$file"
    fi

    echo "Getting and setting up '$file'..."
    wget -P "$dir" "$url"
    chmod u+x "$dir$file"
}

###############################################################################
# Main
###############################################################################

_main() {
    if [[ -z "${1:-}" ]]
    then
        if [[ ! -d "$HOME/bin" ]]
        then
            mkdir "$HOME/bin"
        fi

        _get_script inpval https://github.com/BizTheDad/inpval/raw/main/executable/inpval
        _get_script lockusr https://raw.githubusercontent.com/BizTheDad/scripts/main/lockusr
        _get_script usrgrps https://raw.githubusercontent.com/BizTheDad/scripts/main/usrgrps
    else
        if [[ "${1:-}" =~ ^-h|--help$  ]]
        then
            _print_help
        else
            echo "Invalid option!"
            exit 1
        fi
    fi
}

# Call `_main` after everything has been defined.
_main "$@"
